name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '📚 Documentation'
    label: 'docs'

version-resolver:
  default: patch

template: |
  ## What's Changed
  $CHANGES
