name: Release

on:
  release:
    types: [published]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none
          
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Execute tests
        run: vendor/bin/phpunit

  update-changelog:
    needs: tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Update Changelog
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: [tests, update-changelog]
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify Package Release
        uses: rtCamp/action-discord-notify@v2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_MESSAGE: "New release ${{ github.event.release.tag_name }} of Laravel Magic Auth is now available! \n\nChangelog: ${{ github.event.release.html_url }}"
