name: Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify Package Release
        uses: rtCamp/action-discord-notify@v2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_MESSAGE: "New release ${{ github.event.release.tag_name }} of Laravel Magic Auth is now available! \n\nChangelog: ${{ github.event.release.html_url }}"
